server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/sort;DATABASE_TO_UPPER=false
    username: root
    password: root
    schema: classpath:db/schema-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-database
